/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Fri Dec  9 16:53:37 2016. */

#include "appData.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_AppData_fields[5] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, api_AppData, light, light, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, api_AppData, activation_limit, light, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, api_AppData, switch, activation_limit, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, api_AppData, deactivation_limit, switch, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
