/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Fri Dec 16 16:49:49 2016. */

#include "appData.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_AppData_fields[3] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, api_AppData, light, light, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, api_AppData, activate, light, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
