/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Nov  3 13:37:13 2016. */

#include "appData.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_AppData_fields[2] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, api_AppData, light, light, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
