/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Thu Nov 17 11:48:32 2016. */

#include "sensorData.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_GPS_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, api_GPS, longitude, longitude, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, api_GPS, latitude, longitude, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, api_GPS, altitude, latitude, 0),
    PB_LAST_FIELD
};

const pb_field_t api_SensorData_fields[8] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, api_SensorData, motion, motion, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, api_SensorData, water, motion, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, api_SensorData, temperature_celcius, water, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, api_SensorData, temperature_fahrenheit, temperature_celcius, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, api_SensorData, humidity, temperature_fahrenheit, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, api_SensorData, waterLevel, humidity, 0),
    PB_FIELD(110, UINT32  , REPEATED, CALLBACK, OTHER, api_SensorData, analog_readings, waterLevel, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
